image: rustlang/rust:nightly-bullseye

stages:
  - build
  - test
  - deploy


before_script:
  - apt update
  - apt install -y build-essential cmake clang


# build stable and nightly with bullseye
build:
  stage: build
  script:
    - cargo build

# test nightly
test:
  stage: build
  script:
    - cargo test


# build debian package
deb-bullseye:
  stage: build
  script:
    - cargo install cargo-deb
    - cargo deb
  artifacts:
    paths:
      - target/debian



pages:
  stage: deploy
  only:
    - master
  needs: ["deb-bullseye", "test"]
  script:
    - mkdir -p public
    - cp -vr target/debian/*.deb public/ffdyndns.deb
  artifacts:
    paths:
      - public
