image: rustlang/rust:nightly-buster


stages:
  - build
  - test
  - deploy

cache:
  paths:
    - target

before_script:
  - apt update
  - apt install -y build-essential cmake clang


build-nightly:
  stage: build
  needs: []
  script:
    - cargo build

build-stable:
  stage: build
  image: rust:bullseye
  allow_failure: yes
  script:
    - cargo build


test:
  stage: test
  script:
    - cargo test


deb:
  stage: build
  script:
    - cargo install cargo-deb
    - cargo deb
  artifacts:
    paths:
      - target/debian



pages:
  stage: deploy
  only:
    - master
  needs: ["deb", "test"]
  script:
    - mkdir -p public
    - cp -vr target/debian/*.deb public/ffdyndns.deb
  artifacts:
    paths:
      - public
