image: rustlang/rust:nightly-bullseye


stages:
  - build
  - test
  - deploy

cache:
  paths:
    - target

before_script:
  - apt update
  - apt install -y build-essential cmake clang


# build stable and nightly with bullseye
build-nightly:
  stage: build
  script:
    - cargo build

build-stable:
  stage: build
  image: rust:bullseye
  allow_failure: true
  script:
    - cargo build


# test nightly
test:
  stage: build
  script:
    - cargo test


# build debian package
deb-nightly:
  stage: build
  script:
    - cargo install cargo-deb
    - cargo deb
  artifacts:
    paths:
      - target/debian



pages:
  stage: deploy
  only:
    - master
  needs: ["deb-nightly"]
  script:
    - mkdir -p public
    - cp -vr target/debian/*.deb public/ffdyndns.deb
  artifacts:
    paths:
      - public
