name = "FFdynDNS"
description = "DynDNS Service"
server_web_url = "dnsservice.example.org:8053"
database = "/var/lib/ffdyndns"
dns_server = "127.0.0.1"


[[domain]]
name = "ffdyn.net."
description = "freifunk premium"
allowed_ips = ["0.0.0.0/0", "::/0"]
registration_time = 90
